'use client'

import Link from 'next/link'
import { useState, useEffect, useRef } from 'react'
import { useTheme } from 'next-themes'
import HeroWave from '@/components/ui/dynamic-wave-canvas-background'
import { AuroraBackground } from '@/components/ui/aurora-background'
import { LogoFull } from '@/components/Logo'
import TextCursorProximity from '@/components/ui/text-cursor-proximity'
import { ThemeToggle } from '@/components/ui/theme-toggle'

const NUDGES = [
  {
    category: 'Distraction',
    msg: "You've been on Reddit for 47 minutes. Still feels like 5, right?",
    risk: 78,
    domain: 'reddit.com',
  },
  {
    category: 'Procrastination',
    msg: "Your deadline is 3 hours away. The YouTube tab has been open for 2.",
    risk: 85,
    domain: 'youtube.com',
  },
  {
    category: 'Burnout',
    msg: "34 tab switches in the last hour. Pick one thing and close the rest.",
    risk: 71,
    domain: 'notion.so',
  },
]

const FEATURES = [
  {
    title: 'Frictionless tracking',
    body: 'Installs in under 30 seconds. No setup, no configuration. Just works.',
  },
  {
    title: 'Real-time scoring',
    body: 'Behavior is scored every 30 seconds. You get nudged before the spiral starts.',
  },
  {
    title: 'Context-aware nudges',
    body: 'Messages are generated by AI, tuned to your current behavior — not generic reminders.',
  },
  {
    title: 'Daily insights',
    body: 'One clear summary every evening. Where your time actually went. No noise.',
  },
  {
    title: 'Works during work hours',
    body: 'Set your focus window. LifeLens stays quiet outside of it.',
  },
  {
    title: 'Pause anytime',
    body: 'One click to pause tracking entirely. Your data, your rules.',
  },
]

const NOTS = [
  'No social feed',
  'No endless dashboard to check',
  'No raw browsing history uploaded to any server',
  'No data sold to advertisers',
  'No noise outside your work hours',
  'No credit card to get started',
]

function NudgeCard({
  nudge,
  visible,
}: {
  nudge: (typeof NUDGES)[0]
  visible: boolean
}) {
  const riskColor =
    nudge.risk > 75
      ? 'var(--risk-high)'
      : nudge.risk > 60
      ? 'var(--risk-medium)'
      : 'var(--risk-low)'

  return (
    <div
      style={{
        opacity: visible ? 1 : 0,
        transform: visible ? 'translateY(0)' : 'translateY(10px)',
        transition: 'opacity 0.3s ease, transform 0.3s ease',
      }}
    >
      <div
        className="rounded-xl border p-4"
        style={{ background: 'var(--surface-raised)', borderColor: 'var(--border)' }}
      >
        <div className="flex items-center justify-between mb-3">
          <span
            className="text-xs font-medium px-2 py-0.5 rounded-full"
            style={{ background: 'var(--accent-dim)', color: 'var(--accent)' }}
          >
            {nudge.category}
          </span>
          <div className="flex items-center gap-1.5">
            <div className="w-1.5 h-1.5 rounded-full" style={{ background: riskColor }} />
            <span className="text-xs" style={{ color: 'var(--text-secondary)' }}>
              {nudge.risk}% risk
            </span>
          </div>
        </div>
        <p className="text-sm leading-relaxed" style={{ color: 'var(--text-primary)' }}>
          {nudge.msg}
        </p>
        <div className="flex gap-2 mt-3">
          <button className="text-xs px-3 py-1.5 rounded-lg font-medium lg-btn lg-btn-primary">
            Got it
          </button>
          <button className="text-xs px-3 py-1.5 rounded-lg lg-btn lg-btn-secondary">
            Dismiss
          </button>
        </div>
      </div>
    </div>
  )
}

function BrowserMockup() {
  const [index, setIndex] = useState(0)
  const [visible, setVisible] = useState(true)

  useEffect(() => {
    const interval = setInterval(() => {
      setVisible(false)
      setTimeout(() => {
        setIndex((i) => (i + 1) % NUDGES.length)
        setVisible(true)
      }, 350)
    }, 4000)
    return () => clearInterval(interval)
  }, [])

  const nudge = NUDGES[index]

  return (
    <div
      className="rounded-2xl border overflow-hidden"
      style={{
        background: 'var(--surface)',
        borderColor: 'var(--border)',
        boxShadow: '0 40px 80px rgba(0,0,0,0.5)',
      }}
    >
      {/* Chrome bar */}
      <div
        className="flex items-center gap-1.5 px-4 py-3 border-b"
        style={{ background: 'var(--surface-raised)', borderColor: 'var(--border)' }}
      >
        <div className="w-3 h-3 rounded-full" style={{ background: '#ff5f57' }} />
        <div className="w-3 h-3 rounded-full" style={{ background: '#febc2e' }} />
        <div className="w-3 h-3 rounded-full" style={{ background: '#28c840' }} />
        <div
          className="ml-4 flex-1 rounded-md px-3 py-1 text-xs"
          style={{
            background: 'var(--background)',
            color: 'var(--text-secondary)',
            fontFamily: 'var(--font-geist-mono), monospace',
          }}
        >
          {nudge.domain}
        </div>
      </div>

      {/* Fake page lines */}
      <div className="relative">
        <div className="p-6 space-y-2.5 select-none pointer-events-none" style={{ opacity: 0.15 }}>
          {[80, 55, 90, 40, 70, 60, 45].map((w, i) => (
            <div
              key={i}
              className="h-2 rounded-full"
              style={{ width: `${w}%`, background: 'var(--text-secondary)' }}
            />
          ))}
        </div>

        {/* Nudge overlay */}
        <div className="absolute inset-0 flex items-center justify-center p-5">
          <div className="w-full">
            <NudgeCard nudge={nudge} visible={visible} />
          </div>
        </div>

        <div style={{ height: 80 }} />
      </div>
    </div>
  )
}

export default function LandingPage() {
  const [scrolled, setScrolled] = useState(false)
  const [mounted, setMounted] = useState(false)
  const containerRef = useRef<HTMLDivElement>(null)
  const { resolvedTheme } = useTheme()

  // Defer theme-dependent colors until after mount so server and first client
  // paint always agree — prevents React hydration mismatch.
  const isLight = mounted && resolvedTheme === 'light'
  const heroFromColor = isLight ? '#09090b' : '#fafafa'
  const heroToColor = isLight ? '#0d9488' : '#14b8a6'

  useEffect(() => {
    setMounted(true)
    const onScroll = () => setScrolled(window.scrollY > 40)
    window.addEventListener('scroll', onScroll, { passive: true })
    return () => window.removeEventListener('scroll', onScroll)
  }, [])

  return (
    <div ref={containerRef} className="relative min-h-screen w-full" style={{ background: 'var(--background)' }}>
      {/* Dark mode: animated wave + overlay */}
      {!isLight && (
        <>
          <div className="fixed inset-0 z-0 pointer-events-none">
            <HeroWave />
          </div>
          <div className="fixed inset-0 z-0 pointer-events-none" style={{ background: 'var(--overlay-bg)' }} />
        </>
      )}
      {/* Light mode: aurora background */}
      {isLight && <AuroraBackground showRadialGradient className="pointer-events-none" />}
      {/* All page content — sits above the fixed wave layer */}
      <div className="relative z-10">

      {/* Nav */}
      <nav
        className="fixed top-0 left-0 right-0 z-50 flex items-center justify-between px-8 py-4 transition-all duration-300"
        style={{
          background: scrolled ? 'var(--nav-bg-scrolled)' : 'var(--nav-bg)',
          backdropFilter: 'blur(64px) saturate(200%) brightness(1.05)',
          WebkitBackdropFilter: 'blur(64px) saturate(200%) brightness(1.05)',
          borderBottom: '1px solid var(--nav-border)',
          boxShadow: scrolled ? '0 4px 24px rgba(0,0,0,0.15)' : 'none',
        }}
      >
        <LogoFull size={26} uid="nav" />
        <div className="flex items-center gap-5">
          <ThemeToggle />
          <Link
            href="/login"
            className="text-sm px-4 py-2 rounded-lg font-medium lg-btn lg-btn-secondary"
          >
            Log in
          </Link>
          <Link
            href="/signup"
            className="text-sm px-4 py-2 rounded-lg font-medium lg-btn lg-btn-primary"
          >
            Get started free
          </Link>
        </div>
      </nav>

      {/* Hero */}
      <section className="pt-36 pb-28 px-8 max-w-7xl mx-auto">
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-20 items-center">
          <div>
            <div
              className="inline-flex items-center gap-2 px-3 py-1 rounded-full text-xs font-medium mb-12 border"
              style={{
                background: 'var(--accent-dim)',
                borderColor: 'var(--accent)',
                color: 'var(--accent)',
              }}
            >
              Now in beta
            </div>
            <h1
              className="font-bold tracking-tight leading-[1.04] mb-8 flex flex-col"
              style={{ fontSize: 'clamp(2.75rem, 5vw, 4rem)' }}
            >
              <TextCursorProximity label="Your browser" containerRef={containerRef} radius={120} falloff="gaussian" fromColor={heroFromColor} toColor={heroToColor} toScale={1.15} />
              <TextCursorProximity label="knows when" containerRef={containerRef} radius={120} falloff="gaussian" fromColor={heroFromColor} toColor={heroToColor} toScale={1.15} />
              <TextCursorProximity label="you're losing" containerRef={containerRef} radius={120} falloff="gaussian" fromColor={heroFromColor} toColor={heroToColor} toScale={1.15} />
              <TextCursorProximity label="focus." containerRef={containerRef} radius={120} falloff="gaussian" fromColor={heroFromColor} toColor={heroToColor} toScale={1.15} />
            </h1>
            <p
              className="text-lg leading-relaxed mb-10"
              style={{ color: 'var(--text-secondary)', maxWidth: 380 }}
            >
              LifeLens watches your web behavior in real time and sends intelligent nudges before
              distraction takes hold.
            </p>
            <Link
              href="/signup"
              className="inline-flex items-center justify-center px-6 py-3.5 rounded-xl text-sm font-semibold lg-btn lg-btn-primary"
            >
              Install the extension — it&apos;s free
            </Link>
          </div>

          <div>
            <BrowserMockup />
          </div>
        </div>
      </section>

      {/* Trust bar */}
      <section className="border-y px-8 py-5" style={{ borderColor: 'var(--border)' }}>
        <div className="max-w-7xl mx-auto flex flex-wrap items-center justify-center gap-x-10 gap-y-3">
          {['Privacy-first', 'Local processing', 'No data sold', 'Free during beta', 'GDPR-ready'].map(
            (t) => (
              <span key={t} className="text-sm" style={{ color: 'var(--text-secondary)' }}>
                {t}
              </span>
            )
          )}
        </div>
      </section>

      {/* Statement */}
      <section className="px-8 py-32 max-w-5xl mx-auto">
        <p
          className="font-semibold leading-[1.25] tracking-tight"
          style={{ color: 'var(--text-primary)', fontSize: 'clamp(1.75rem, 3.5vw, 2.5rem)' }}
        >
          Most productivity tools track what you{' '}
          <span style={{ color: 'var(--text-secondary)' }}>finish</span>.
          <br />
          LifeLens watches what you{' '}
          <span style={{ color: 'var(--text-primary)' }}>actually do</span>.
        </p>
        <p className="mt-8 text-lg leading-relaxed max-w-xl" style={{ color: 'var(--text-secondary)' }}>
          Your browser holds the unfiltered record of your digital life. We read that signal and
          turn it into something useful — honest feedback, delivered at the right moment.
        </p>
      </section>

      {/* How it works */}
      <section className="border-t px-8 py-24" style={{ borderColor: 'var(--border)' }}>
        <div className="max-w-7xl mx-auto">
          <p
            className="text-xs uppercase tracking-widest mb-16"
            style={{ color: 'var(--text-secondary)' }}
          >
            How it works
          </p>
          <div
            className="grid grid-cols-1 md:grid-cols-3"
            style={{ borderTop: '1px solid var(--border)', borderLeft: '1px solid var(--border)' }}
          >
            {[
              {
                n: '01',
                title: 'Install. Done.',
                body: 'A lightweight Chrome extension. No accounts needed to start — just install and it begins watching in the background.',
              },
              {
                n: '02',
                title: 'Behavior is scored.',
                body: 'Every 30 seconds, the AI engine evaluates your tab activity, session duration, and switching patterns to calculate a live risk score.',
              },
              {
                n: '03',
                title: 'You get nudged.',
                body: 'When risk crosses the threshold, a context-aware nudge appears — designed to interrupt just enough to redirect your attention.',
              },
            ].map((step) => (
              <div
                key={step.n}
                className="p-8 md:p-10"
                style={{
                  borderRight: '1px solid var(--border)',
                  borderBottom: '1px solid var(--border)',
                }}
              >
                <span
                  className="text-xs"
                  style={{
                    color: 'var(--text-secondary)',
                    fontFamily: 'var(--font-geist-mono), monospace',
                  }}
                >
                  {step.n}
                </span>
                <h3
                  className="text-xl font-semibold mt-5 mb-3"
                  style={{ color: 'var(--text-primary)' }}
                >
                  {step.title}
                </h3>
                <p className="text-sm leading-relaxed" style={{ color: 'var(--text-secondary)' }}>
                  {step.body}
                </p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Feature grid */}
      <section className="border-t px-8 py-24" style={{ borderColor: 'var(--border)' }}>
        <div className="max-w-7xl mx-auto">
          <p
            className="text-xs uppercase tracking-widest mb-4"
            style={{ color: 'var(--text-secondary)' }}
          >
            Features
          </p>
          <h2
            className="font-bold tracking-tight mb-16"
            style={{ color: 'var(--text-primary)', fontSize: 'clamp(1.75rem, 3vw, 2.5rem)' }}
          >
            Built to fit inside your day,
            <br />
            not interrupt it.
          </h2>
          <div
            className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3"
            style={{ borderTop: '1px solid var(--border)', borderLeft: '1px solid var(--border)' }}
          >
            {FEATURES.map((f) => (
              <div
                key={f.title}
                className="p-8"
                style={{
                  borderRight: '1px solid var(--border)',
                  borderBottom: '1px solid var(--border)',
                }}
              >
                <h3 className="text-sm font-semibold mb-2" style={{ color: 'var(--text-primary)' }}>
                  {f.title}
                </h3>
                <p className="text-sm leading-relaxed" style={{ color: 'var(--text-secondary)' }}>
                  {f.body}
                </p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* What it's NOT */}
      <section className="border-t px-8 py-24" style={{ borderColor: 'var(--border)' }}>
        <div className="max-w-7xl mx-auto grid grid-cols-1 lg:grid-cols-2 gap-20 items-start">
          <div className="lg:sticky lg:top-32">
            <p
              className="text-xs uppercase tracking-widest mb-4"
              style={{ color: 'var(--text-secondary)' }}
            >
              What LifeLens is not
            </p>
            <h2
              className="font-bold tracking-tight"
              style={{ color: 'var(--text-primary)', fontSize: 'clamp(1.75rem, 3vw, 2.5rem)' }}
            >
              A tool that respects
              <br />
              your time and
              <br />
              your data.
            </h2>
          </div>
          <div>
            {NOTS.map((item) => (
              <div
                key={item}
                className="flex items-center gap-5 py-5 border-b"
                style={{ borderColor: 'var(--border)' }}
              >
                <div
                  className="w-5 h-px flex-shrink-0"
                  style={{ background: 'var(--text-secondary)' }}
                />
                <span className="text-base" style={{ color: 'var(--text-secondary)' }}>
                  {item}
                </span>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Nudge showcase */}
      <section className="border-t px-8 py-24" style={{ borderColor: 'var(--border)' }}>
        <div className="max-w-7xl mx-auto">
          <p
            className="text-xs uppercase tracking-widest mb-4"
            style={{ color: 'var(--text-secondary)' }}
          >
            Real nudges
          </p>
          <h2
            className="font-bold tracking-tight mb-16"
            style={{ color: 'var(--text-primary)', fontSize: 'clamp(1.75rem, 3vw, 2.5rem)' }}
          >
            Honest. Specific.
            <br />
            Timed to actually help.
          </h2>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-5">
            {NUDGES.map((n) => (
              <NudgeCard key={n.msg} nudge={n} visible={true} />
            ))}
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="border-t px-8 py-36 text-center" style={{ borderColor: 'var(--border)' }}>
        <div className="max-w-2xl mx-auto">
          <h2
            className="font-bold tracking-tight mb-6"
            style={{ color: 'var(--text-primary)', fontSize: 'clamp(2rem, 4vw, 3.25rem)' }}
          >
            Start paying attention
            <br />
            to your attention.
          </h2>
          <p className="text-lg mb-10" style={{ color: 'var(--text-secondary)' }}>
            Free during beta. Install in under 30 seconds. No credit card required.
          </p>
          <Link
            href="/signup"
            className="inline-flex items-center justify-center px-8 py-4 rounded-xl text-base font-semibold lg-btn lg-btn-primary"
          >
            Get started free
          </Link>
        </div>
      </section>

      {/* Footer */}
      <footer
        className="px-8 py-8"
        style={{
          background: 'var(--footer-bg)',
          backdropFilter: 'blur(64px) saturate(200%) brightness(1.05)',
          WebkitBackdropFilter: 'blur(64px) saturate(200%) brightness(1.05)',
          borderTop: '1px solid var(--glass-border)',
        }}
      >
        <div className="flex flex-col sm:flex-row items-center justify-between gap-4">
          <LogoFull size={22} uid="footer" />
          <div className="flex items-center gap-6">
            <Link
              href="/login"
              className="text-xs hover:opacity-80 transition-opacity"
              style={{ color: 'var(--text-secondary)' }}
            >
              Log in
            </Link>
            <Link
              href="/signup"
              className="text-xs hover:opacity-80 transition-opacity"
              style={{ color: 'var(--text-secondary)' }}
            >
              Sign up
            </Link>
            <span className="text-xs" style={{ color: 'var(--text-secondary)' }}>
              Privacy-first. Your data stays yours.
            </span>
          </div>
        </div>
        <div
          className="mt-6 pt-6 text-center text-xs"
          style={{ borderTop: '1px solid var(--glass-border)', color: 'var(--text-secondary)' }}
        >
          © 2026 LifeLens. All rights reserved.
        </div>
      </footer>
      </div>{/* end content wrapper */}
    </div>
  )
}
